# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\student\Documents\YEP\PYQT2\Peka\Mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_order = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_order.setGeometry(QtCore.QRect(110, 170, 75, 23))
        self.pushButton_order.setObjectName("pushButton_order")
        self.spinBox_amount = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_amount.setGeometry(QtCore.QRect(190, 170, 42, 22))
        self.spinBox_amount.setMinimum(1)
        self.spinBox_amount.setObjectName("spinBox_amount")
        self.textEdit_output = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_output.setGeometry(QtCore.QRect(350, 10, 431, 591))
        self.textEdit_output.setObjectName("textEdit_output")
        self.spinBox_courier = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_courier.setGeometry(QtCore.QRect(190, 120, 42, 22))
        self.spinBox_courier.setFrame(True)
        self.spinBox_courier.setReadOnly(False)
        self.spinBox_courier.setObjectName("spinBox_courier")
        self.spinBox_Baker = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Baker.setGeometry(QtCore.QRect(190, 80, 42, 22))
        self.spinBox_Baker.setObjectName("spinBox_Baker")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 80, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 120, 47, 13))
        self.label_2.setObjectName("label_2")
        '''
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        '''
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_order.setText(_translate("MainWindow", "Order"))
        self.label.setText(_translate("MainWindow", "Baker"))
        self.label_2.setText(_translate("MainWindow", "Courier"))
